# Generated by Django 3.1 on 2020-08-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200810_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
